package main

import "fmt"

// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed
// four million, find the sum of the even-valued terms.

func fib(n int32) int32 {
	if n < 2 {
		return n
	}
	return fib(n-1) + fib(n-2)
}

func main() {
	var i int32 = 2
	var sum int32 = 0
	for {
		result := fib(i)
		if result >= 4000000 {
			break
		} else if result%2 == 0 {
			sum += result
		}
		i++
	}

	fmt.Print(sum)
}
